### ISSUE TITLE
LinOTP check

### ISSUE THREAD

**Issue by trustbyte** [CERN-CERT/pam_2fa#3]
Hey!

I am trying to use pam_2fa with a LinOTP server (HMAC token) and the check is like this:
https://lin_otp_server.domain/validate/simplecheck?pass=OTP_CODE&user=username

The pam_2fa has built in for google authenticator, is it possible to add the check for the LinOTP?

**Comment by Feandil** [comment]
Hi!

Unfortunately, this part of the code, `gauth.c`, was built to support a SOAP service used at CERN that can do Gauth validations, it cannot be adapted via configuration to LinOTP....

Writing a plugin that simply do a REST call with the OTP it's given should be straight forward (leaving all options in configurations. We don't have manpower for this by pull request are welcome!

**Comment by trustbyte** [comment]
ok, thanks!
