### ISSUE TITLE
Make changes to PAM sequence based on pubkey auth

### ISSUE THREAD

**Issue by bbockelm** [CERN-CERT/pam_2fa#6]
We are working on adapting our local site to use 2FA and want to utilize the lovely `pam_ssh_user_auth` to help ensure it applies for both pubkey and password auth.

However, we have a new twist --

_If we have a session coming from a limited set of known IPs, we want to allow the session to skip 2FA for pubkey auth._

The only way I can think of doing this is adding an argument to the invocation of `pam_ssh_user_auth` so the module only succeeds for a single specific auth method.

That looks like it's not possible with the current code but possibly a small tweak?  Is there a way to do this without code changes?

**Comment by Feandil** [comment]
I think it should be possible in the SSHD configuration itself.
I guess that for supporting password plus pubkey authentication you currently have in your SSHD configuration:
```
AuthenticationMethods publickey,keyboard-interactive:pam keyboard-interactive:pam,keyboard-interactive:pam
```
(and using pam_ssh_user_auth to then run different pam paths if there was a successful authentication before)

You can simply have a different AuthenticationMethods for special IPs/users/etc (match criteria).
For example, 2FA for password only from 127.0.0.1&127.0.0.2 would be:
```
Match Address 127.0.0.1,127.0.0.2
  AuthenticationMethods publickey keyboard-interactive:pam,keyboard-interactive:pam
```
(i.e. not having a pam call to verify 2FA after pubkey)

At CERN e.g. we sometime disable 2FA fully with:
```
Match Address 127.0.0.1,127.0.0.2
  AuthenticationMethods publickey keyboard-interactive:pam
```

Let me know if I understood your problem correctly and if it works (or not)

**Comment by bbockelm** [comment]
Ah yes, I do think that will work.  Thanks!
